### ISSUE TITLE
Rule34 command incorrectly handle query with multiple words

### ISSUE THREAD

**Issue by montoner0** [hibikidesu/NekoBot#10]
It looks like the query should be escaped. Otherwise it ignore words excepting a first one.

**Comment by CFTheMaster** [comment]
we will look into it

**Comment by montoner0** [comment]
I wonder why this issue was closed. The bug is still there. Just try multi-word request with rule34.

**Comment by hibikidesu** [comment]
Command only takes 1 argument

**Comment by montoner0** [comment]
Why it can't take all of them?
